services:
  postgres:
    image: postgres:latest
    container_name: webdev_starter
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webdev_starter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

networks:
  my_app_network:
    name: webdev_starter_network
